### ISSUE TITLE
PprzGCS crash when trying to draw lines on map

### ISSUE THREAD

**Issue by jesusBV20** [Fabien-B/GcsAgain#11]
Hi Fabien,

I have been testing your new GCS tool and I realised that the program crash when it tries to execute a flight plan block that needs to draw lines or circles on the map. When it happens the following lines apears in the console:

"
terminate called after throwing an instance of 'std::bad_any_cast'
  what():  bad any_cast
"

My PprzGCS root folder is in /sw/ext and I ran the builder without errors. I compiled the "Quad_Navstik" and "Microjet" examples to test it.

**Comment by Fabien-B** [comment]
Hi,
Try with the latest version, it should be fixed now with https://github.com/Fabien-B/PprzGCS/commit/76bd3371ecb8d8b4867875f8eada86de9a4acdcc (I think...). 
I understand you build it from sources? If not, tell me, I will trigger a new build for the .deb.

**Comment by jesusBV20** [comment]
Yes I built it from source. It works perfectly now, thanks you so much for your fast answer. The problem was a variable overflowing??

**Comment by Fabien-B** [comment]
Cool!
The lib used to access messages field need as input a reference to a variable with the right type.
I changed some time ago in pprzlink some messages fields from `float` to `double`, because poor float precision was misplacing waypoints on the map.
The GCS then declared `double` variables, but I think you use an older version of paparazzi (before July 1st ?), so the lib expected `float`.
I just wrote a wrapper function that try both and catch this exception.

**Comment by Fabien-B** [comment]
If the waypoints are not placed exactly where they should be, or if you see that the track of the aircraft is not smooth, update paparazzi to a newer version.
The old GCS does not have this issue because in OCaml, a `Float` is like a `double` in C++, and there is no 32 bits float.
